[project]
name = "a2-language-model"
version = "0.1.0"
description = "Language Model Assignment - NLU Course"
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "torch>=2.7.0",
    "datasets>=2.14.0",
    "tqdm>=4.65.0",
    "numpy>=1.24.0",
    "jupyter>=1.0.0",
    "ipykernel>=6.25.0",
    "flask>=3.0.0",
    "matplotlib>=3.10.8",
]

[tool.uv]
index-url = "https://pypi.org/simple"

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu128" }
